### ISSUE TITLE
Why did I get this command wrong?

### ISSUE THREAD

**Issue by ZhouGuangP** [Jeeseung-Park/VIPLO#1]
![image](https://user-images.githubusercontent.com/108053656/235854539-15ce4264-2e94-42a6-b7a5-554dc326abdd.png)

**Comment by Jeeseung-Park** [comment]
Hi, thanks for the reporting.
The download script runs fine for me. 
I recommend updating gdown version to latest version. 
If the problem persists, you can download upt weight at [here](https://drive.google.com/file/d/1kkyVeoUGb8rT9b5J5Q3f51OFmm4Z73UD/view) and move weight to `upt/weight/` folder.

**Comment by ZhouGuangP** [comment]
> Hi, thanks for the reporting. The download script runs fine for me. I recommend updating gdown version to latest version. If the problem persists, you can download upt weight at [here](https://drive.google.com/file/d/1kkyVeoUGb8rT9b5J5Q3f51OFmm4Z73UD/view) and move weight to `upt/weight/` folder.
Hi, thanks for your answer. I updated the gdown version to latest version, but it still doesn't work.  
And I have another request, can you give me the results of "bash download/download_det_pose.sh", "bash download/download_vitpose_weight.sh ", and"bash download/download_checkpoint.sh"?

**Comment by ZhouGuangP** [comment]
> Hi, thanks for the reporting. The download script runs fine for me. I recommend updating gdown version to latest version. If the problem persists, you can download upt weight at [here](https://drive.google.com/file/d/1kkyVeoUGb8rT9b5J5Q3f51OFmm4Z73UD/view) and move weight to `upt/weight/` folder.
OK, Thanks for your reply, I found it's my network error.
