### ISSUE TITLE
Joint Attention Weight

### ISSUE THREAD

**Issue by zhumanli** [Jeeseung-Park/VIPLO#2]
Hi,

I'm wondering why αij is the joint attention weight in equation (2), in my understanding, it is the attention weight between the ith human and jth object. Can you further explain a bit? Thank you very much.
![image](https://user-images.githubusercontent.com/42202802/236686215-80d69829-0436-4894-ae1e-6d15bddce9ef.png)

**Comment by Jeeseung-Park** [comment]
Sorry for the late reply.
Kij is the pairwise joint feature for the ith human and jth object, it contains different feature for each human joint. So Kij tensor shape looks like 17(keypoint number) x C(channel dimension) and Qij tensor shape looks like 1 x C.

**Comment by zhumanli** [comment]
Thank you very much for your detailed explanation, this is very helpful!
