### ISSUE TITLE
Instructions for VCOCO

### ISSUE THREAD

**Issue by zhumanli** [Jeeseung-Park/VIPLO#6]
Hi,

By any chance you could provide VCOCO instructions and running scripts? Thank you so much.

**Comment by Jeeseung-Park** [comment]
Since our code is heavily based on [spatially-conditioned-graphs implementation](https://github.com/fredzzhang/spatially-conditioned-graphs), you can refer to the v-coco instruction on the github. 
Thank you.

**Comment by zhumanli** [comment]
Sure! Thank you very much!
